Should forget about all this.

diff --git a/bin/CAdir b/bin/CAdir
--- a/bin/CAdir
+++ b/bin/CAdir
@@ -8,11 +8,17 @@ cat <<USAGE
 USAGE
 }
 
-case "${1:-}" in
-  -h|'-?'|--help)   usage ; exit 0 ;;
-  "")               echo 'No directory given.' 1>&2 ; exit 1 ;;
-  *)                cd "$1"  ;;
-esac
+declare -A CAdir=( [--syslog]=true [root]="" )
+while [[ "${1:-}" != "" ]]
+do
+  case "${1:-}" in
+    -h|'-?'|--help) usage ; exit 0 ;;
+    --syslog)       CAdir[--syslog]=true ;;
+    --no-syslog)    CAdir[--syslog]=false ;;
+    *)              CAdir[root]="$1" ;;
+  esac
+  shift
+done
 
 
 ## Logging niceties.
@@ -20,22 +26,46 @@ esac
 function timestamp {
   date --utc +%FT%TZ
 }
-function log {
-  logger -p user.$2 -- "$1"
-  printf "%s\n" -- "$(timestamp) $1"
+function syslog {
+  if ${CAdir[--syslog]}
+  then
+    sed -r 's/^.{20} -CAdir- //' | logger -i -p user.info
+  else
+    cat > /dev/null
+  fi
 }
+function lockedlog {
+  flock --timeout 0.5 --exclusive ./CAdir/log tee ./CAdir/log 
+}
+
 function msg {
-  log "$1" info 1>&2
+  printf "%s\n" -- "$(timestamp) -CAdir- $1"
+}
+function info {
+  msg "$1"
 }
 function err {
-  log "$1" err
+  msg "$1"
   exit 1
 }
 
 
-
-function lockingly {
-  ( flock --exclusive 1
-    ) 1>./CAdir/log 2>&1
+function main {
+  { [[ -n "${CAdir[root]}" ]] || err "No CA dir given."
+    if cd "${CAdir[root]}" 2>&1
+    then
+      info "Changed directory to \`${CAdir[root]}'."
+    else
+      err "Failed to change directory to \`${CAdir[root]}'."
+    fi
+    [[ -d ./CAdir ]] || { info "Creating \`./CAdir/log'."
+                          mkdir -p ./CAdir 2>&1           ;} 
+    info "Locking \`./CAdir/log'."
+    { info "User is \`$(whoami)'."
+      wc -l 1>&2
+      info "Finished."            ;} | lockedlog
+    info "Unlocked."                                          ;} | syslog
 }
+
+main
 
